/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JSO.Com.ControllPanels;

import JSO.Com.Main.ImagePanel;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author shayan
 */
public class PanelFixFrame extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form TeamInfo
     */
    
    ImagePanel imagePanel, imagePanel1;
    ControllPanelx ControllPanelx;
    String path;
    int picnumber =99 ;
    
    
    public PanelFixFrame(ControllPanelx cInterface, String addPath) {
        initComponents();
        this.ControllPanelx = cInterface;
        path = addPath;
        init2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButtonRemoveImage = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jPanelForPlayers = new javax.swing.JPanel();
        jPanelImagees_old = new javax.swing.JPanel();
        jPanelImagees = new javax.swing.JPanel();
        jPanelsubstitution = new javax.swing.JPanel();
        jPanelIMG1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setText("صورت گیری");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("حذف تصویر");
        jPanel7.add(jLabel2);

        jToggleButtonRemoveImage.setText("حذف انتخابی");
        jToggleButtonRemoveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRemoveImageActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButtonRemoveImage);

        jButton1.setText("حذف همه");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jPanel2.add(jPanel7);

        jPanel6.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("نمایش تمام صفحه");
        jPanel6.add(jLabel1);

        jToggleButton1.setText("نمایش ");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton1);

        jButton3.setText("بروز رسانی");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanelForPlayers.setLayout(new java.awt.GridLayout(0, 1));

        jPanelImagees_old.setLayout(new java.awt.BorderLayout());

        jPanelImagees.setMaximumSize(new java.awt.Dimension(2500, 2400));
        jPanelImagees.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanelImagees.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanelImagees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelImageesMousePressed(evt);
            }
        });
        jPanelImagees.setLayout(new java.awt.GridLayout(1, 0));
        jPanelImagees_old.add(jPanelImagees, java.awt.BorderLayout.WEST);

        jPanelsubstitution.setMinimumSize(new java.awt.Dimension(83, 120));
        jPanelsubstitution.setPreferredSize(new java.awt.Dimension(83, 120));
        jPanelsubstitution.setLayout(new java.awt.GridLayout(0, 1));

        jPanelIMG1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelIMG1.setLayout(new java.awt.GridLayout(1, 0));
        jPanelsubstitution.add(jPanelIMG1);

        jPanelImagees_old.add(jPanelsubstitution, java.awt.BorderLayout.CENTER);

        jPanelForPlayers.add(jPanelImagees_old);

        jPanel1.add(jPanelForPlayers, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        updateLastonair();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            jPanelsubstitution.setBackground(Color.RED);
//            showTeamInfoOn();
            ControllPanelx.showFixOn(picnumber, 1, path);
        } else {
            jPanelsubstitution.setBackground(Color.GRAY);
//            showTeamInfoOff();
            ControllPanelx.showFixOff(picnumber, 2);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        selectframe();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButtonRemoveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRemoveImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonRemoveImageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        removeAllPics();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanelImageesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelImageesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelImageesMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelForPlayers;
    private javax.swing.JPanel jPanelIMG1;
    private javax.swing.JPanel jPanelImagees;
    private javax.swing.JPanel jPanelImagees_old;
    private javax.swing.JPanel jPanelsubstitution;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonRemoveImage;
    // End of variables declaration//GEN-END:variables
  

    private void init2() {
        imagePanel = new ImagePanel();
        imagePanel1 = new ImagePanel();
//        jPanelPic.add(imagePanel);
        jPanelIMG1.add(imagePanel1);
        imagePanel.reloadImage();
        updateUI();

    }

    private void updateLastonair() {
//  cInterface.updateSend(playernamedata);
        ControllPanelx.showFixOn(picnumber, 0, path);
    }

    private void initData() {
        imagePanel.redrawImage();
        updateUI();
    }

    private void selectframe() {
        javax.swing.JFrame f1 = new javax.swing.JFrame("dsj - play movie");
        java.awt.FileDialog fd = new java.awt.FileDialog(new JFrame("انتخاب عکس"), "انتخاب تصاویر", java.awt.FileDialog.LOAD);
fd.setMultipleMode(true);
fd.setDirectory(path);
		fd.setVisible(true);

		if (fd.getFile() == null) return;
                else {
                     File[] files = fd.getFiles();

            for (int i = 0; i < files.length; i++) {

                final ImagePanel ix = new ImagePanel(files[i]);

                ix.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        selectPic2(evt, ix);
                    }
                });

//                ix.addMouseListener(new java.awt.event.MouseAdapter() {
//                    public void mouseClicked(java.awt.event.MouseEvent evt) {
//                        selectPic2(evt, ix);
//                      //  new Sounds().playselectZangBlur();
//                    }
//
//                });
                jPanelImagees.add(ix);
                if (jPanelImagees.getComponentCount() > 2) {
                    if (jPanelImagees.getComponentCount() > 5) {
                        if (jPanelImagees.getComponentCount() > 10) {
                            jPanelImagees.setLayout(new java.awt.GridLayout(4, 0));
                        } else {
                            jPanelImagees.setLayout(new java.awt.GridLayout(3, 0));
                        }
                    } else {
                        jPanelImagees.setLayout(new java.awt.GridLayout(2, 0));
                    }
                } else {
                    jPanelImagees.setLayout(new java.awt.GridLayout(1, 0));
                }
            }
            jPanelImagees.updateUI();
        }
    }

    private void selectPic2(java.awt.event.MouseEvent evt, ImagePanel ix) {
        if (jToggleButtonRemoveImage.isSelected()) {
            jToggleButtonRemoveImage.setSelected(false);
            jPanelImagees.remove(ix);
            jPanelImagees.updateUI();
        } else {
            imagePanel1.drawImage(ix.getAddress());
            this.path = ix.getAddress();
            imagePanel1.updateUI();
        }
    }



    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("mclick");
    }

    @Override
    public void mousePressed(MouseEvent e) {
        System.out.println("mpress");
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        System.out.println("mrelese");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        System.out.println("menter");
    }

    @Override
    public void mouseExited(MouseEvent e) {
        System.out.println("mouseExited");
    }

    private void removeAllPics() {
        jPanelImagees.removeAll();
        jPanelImagees.updateUI();
    }

}
