/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JSO.Com.ControllPanels;

import JSO.Com.DataBox_cutom.DatabaseMain;
import JSO.Com.DataBox_cutom.DatabaseMain.VIsanimBool;

/**
 *
 * @author Shayan
 */
public class PanelVisAnimBool extends javax.swing.JPanel {

    /**
     * Creates new form VisAnimBool
     */
    public PanelVisAnimBool() {
        initComponents();
    }

    
    PanelVisAnimBool(DatabaseMain.VIsanimBool visanimbools) {
          initComponents();
//                System.out.println("981105    visanimbools="+ visanimbools.getId());
//                 System.out.println("981105sss     visanimbools ="+ jSpinnerObjectID);
      jSpinnerObjectID.setValue(visanimbools.getId());
      jCheckBoxVis.setSelected(visanimbools.isVis());
            jCheckBoxVisActive.setSelected(visanimbools.isVisActive());
      jCheckBoxAnim.setSelected(visanimbools.isAnim());
      jSpinnerObjecdim.setValue(visanimbools.getDim());
       jCheckBoxCOLOR.setSelected(visanimbools.isColor());
     jCheckBoxseq.setSelected(visanimbools.isSeq());
                
    }
  public   VIsanimBool getVisAnimBool(DatabaseMain.VIsanimBool visanimbools){
  //   DatabaseMain.VIsanimBool   d =  DatabaseMain.VIsanimBool(0, true, true, 1, true, true);
   visanimbools.setId((int)jSpinnerObjectID.getValue());
    visanimbools.setDim((int)jSpinnerObjecdim.getValue());
     visanimbools.setAnim(jCheckBoxAnim.isSelected());
       visanimbools.setColor(jCheckBoxCOLOR.isSelected());
        
           visanimbools.setSeq(jCheckBoxseq.isSelected());
             visanimbools.setVis(jCheckBoxVis.isSelected());
              visanimbools.setVisActive(jCheckBoxVisActive.isSelected());
             
             //= new DatabaseMain.VIsanimBool((int)jSpinnerObjectID.getValue(), jCheckBoxVis.isSelected(), jCheckBoxAnim.isSelected(), (int)jSpinnerObjecdim.getValue(), jCheckBoxCOLOR.isSelected(), jCheckBoxseq.isSelected());
  return visanimbools;
  }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerObjectID = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxVisActive = new javax.swing.JCheckBox();
        jCheckBoxVis = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jSpinnerObjecdim = new javax.swing.JSpinner();
        jCheckBoxAnim = new javax.swing.JCheckBox();
        jCheckBoxCOLOR = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxseq = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");
        jPanel4.add(jLabel1);

        jSpinnerObjectID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jSpinnerObjectID.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel4.add(jSpinnerObjectID);

        add(jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout());

        jCheckBoxVisActive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxVisActive.setText("Act");
        jPanel1.add(jCheckBoxVisActive);

        jCheckBoxVis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxVis.setText("Vis");
        jPanel1.add(jCheckBoxVis);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout());

        jSpinnerObjecdim.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jSpinnerObjecdim.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerObjecdim);

        jCheckBoxAnim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxAnim.setText("Dim");
        jPanel2.add(jCheckBoxAnim);

        jCheckBoxCOLOR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxCOLOR.setText("Col");
        jPanel2.add(jCheckBoxCOLOR);

        add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridLayout());

        jCheckBoxseq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxseq.setText("Sequence");
        jPanel3.add(jCheckBoxseq);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxAnim;
    private javax.swing.JCheckBox jCheckBoxCOLOR;
    private javax.swing.JCheckBox jCheckBoxVis;
    private javax.swing.JCheckBox jCheckBoxVisActive;
    private javax.swing.JCheckBox jCheckBoxseq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinnerObjecdim;
    private javax.swing.JSpinner jSpinnerObjectID;
    // End of variables declaration//GEN-END:variables
}
