/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JSO.Com.ControllPanels;

import JSO.Com.DataBox_cutom.DatabaseMain;

/**
 *
 * @author Shayan
 */
public class PanelAnimationStartEnd extends javax.swing.JPanel {

    /**
     * Creates new form AnimationStartEnd
     */
    public PanelAnimationStartEnd() {
        initComponents();
    }

    PanelAnimationStartEnd(DatabaseMain.animRateFromENd aRateFromENds) {
         initComponents();
       jSpinnerObjectID.setValue(aRateFromENds.getId());
        jSpinnerrate.setValue(aRateFromENds.getFrameRate());
        jCheckBoxStartEndEn.setSelected(aRateFromENds.isStartendEn());
         jSpinnerAnimStart.setValue(aRateFromENds.getStart());
          jSpinnerAnimEnd.setValue(aRateFromENds.getEnd());
    }
    
    public DatabaseMain.animRateFromENd getAnimationStartEnd(DatabaseMain.animRateFromENd aRateFromENds) {
        
        aRateFromENds.setId((int) jSpinnerObjectID.getValue());
         aRateFromENds.setFrameRate((int) jSpinnerrate.getValue());
         aRateFromENds.setStartendEn(jCheckBoxStartEndEn.isSelected());
          aRateFromENds.setStart((int) jSpinnerAnimStart.getValue());
           aRateFromENds.setEnd((int) jSpinnerAnimEnd.getValue());
          return aRateFromENds;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerObjectID = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerrate = new javax.swing.JSpinner();
        jCheckBoxStartEndEn = new javax.swing.JCheckBox();
        jSpinnerAnimStart = new javax.swing.JSpinner();
        jSpinnerAnimEnd = new javax.swing.JSpinner();

        setLayout(new java.awt.GridLayout(1, 0));

        jSpinnerObjectID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jSpinnerObjectID.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(jSpinnerObjectID);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AnimRate");
        add(jLabel1);

        jSpinnerrate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jSpinnerrate.setModel(new javax.swing.SpinnerNumberModel());
        add(jSpinnerrate);

        jCheckBoxStartEndEn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxStartEndEn.setText("StartEnd");
        add(jCheckBoxStartEndEn);

        jSpinnerAnimStart.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jSpinnerAnimStart.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(jSpinnerAnimStart);

        jSpinnerAnimEnd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jSpinnerAnimEnd.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(jSpinnerAnimEnd);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxStartEndEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinnerAnimEnd;
    private javax.swing.JSpinner jSpinnerAnimStart;
    private javax.swing.JSpinner jSpinnerObjectID;
    private javax.swing.JSpinner jSpinnerrate;
    // End of variables declaration//GEN-END:variables
}
